### ISSUE TITLE
add sorces failes on ubuntu 22.04

### ISSUE THREAD

**Issue by vkuehn** [openplotter/docs#16]
just installed open plotter in a VM on ubuntu 22.04 LTS. when adding sources it fails with

creating configuration directory /home/root/.openplotter
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openplotterSettings/installSources.py", line 25, in main
    conf2 = Conf()
  File "/usr/lib/python3/dist-packages/openplotterSettings/conf.py", line 38, in __init__
    os.mkdir(self.conf_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/.openplotter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/settingsSourcesInstall", line 11, in <module>
    load_entry_point('openplotterSettings==3.6.6', 'console_scripts', 'settingsSourcesInstall')()
  File "/usr/lib/python3/dist-packages/openplotterSettings/installSources.py", line 103, in main
    except Exception as e: print(_('FAILED: ')+str(e))
NameError: name '_' is not defined

what can I do to fix that ?
is that a bug ? if so which script runs here ?

**Comment by vkuehn** [comment]
taking the issue to the settings repo
